export {
  CredentialStoreError,
  PROFILE_KINDS,
  createOfficialCredentialAdapter,
  credentialPaths,
  importCredentialProfile,
  initCredentialStore,
  inspectCredentialProfile,
  listCredentialProfiles,
  markCredentialProfileState,
  parseCredentialJson,
  profileFromEnvironment,
  profileFromSecureSource,
  reconcileCredentialOperation,
  recordVerifiedCredentialScopes,
  recoverCredentialProfile,
  removeCredentialProfile,
  resolveCredentialProfile,
  resolveOfficialCredentialAdapter,
  setDefaultCredentialProfile,
  validateCredentialStore,
  withCredentialProfileOperation
} from '@mcp/engine/credentials';
